service: express-serverless
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
package:
  exclude:
    - node_modules/**
    - src/**

functions:
  app:
    handler: src/app.handler
    environment:
      MYSQL_PASSWORD: '#Asad2001g_'
      MYSQL_DB: tododb
      MYSQL_USER: root
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_SSL: "true"
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 4002
    httpPort: 4000